name: Build macOS App

on:
  repository_dispatch:
    types: [release_created]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write # Grant write permissions for uploading release assets

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --release

      - name: Archive macOS App
        run: |
          mkdir -p macos-build
          cp -r build/macos/Build/Products/Release/*.app macos-build/
          zip -r consistency-tracker-macos-${{ github.event.client_payload.tag }}.zip macos-build/*
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.client_payload.release_id }}/assets{?name}
          asset_path: consistency-tracker-macos-${{ github.event.client_payload.tag }}.zip
          asset_name: consistency-tracker-macos-${{ github.event.client_payload.tag }}.zip
          asset_content_type: application/zip
