name: Build Windows App

on:
  repository_dispatch:
    types: [release_created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Parse Release Info
        id: parse_release
        run: |
          $eventPayload = Get-Content -Raw -Path $env:GITHUB_EVENT_PATH | ConvertFrom-Json
          echo "RELEASE_ID=$($eventPayload.client_payload.release_id)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TAG=$($eventPayload.client_payload.tag)" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          enable-windows: true
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release
        
      - name: Archive Windows Executable
        run: |
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath "consistency-tracker-windows-${{ env.TAG }}.zip"
        shell: pwsh # Use PowerShell for Compress-Archive

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets{?name}
          asset_path: consistency-tracker-windows-${{ env.TAG }}.zip
          asset_name: consistency-tracker-windows-${{ env.TAG }}.zip
          asset_content_type: application/zip